import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin, AiFillInstagram, AiFillGithub } from "react-icons/ai"
import Image from 'next/image';
import Memoji from '../public/Untitled.png';
import one from '../public/one.jpg';
import two from '../public/two.jpg';
import three from '../public/three.jpg';
import View from '../public/cars1.png'
import View2 from '../public/View3.png'
import View3 from '../public/Vi.png'
import View4 from '../public/v34.png'
import View5 from '../public/vi56.png'
import four from '../public/four.jpg';
import { useState } from 'react';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Gift Letuka's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' px-10 w-screen dark:bg-gray-400  ' >
        <section className='w-auto flex flex-col items-center text-center '>
          <nav className='bg-white h-14  w-96 rounded-full flex flex-row gap-28  mt-14   '>
            <h1 className='text-2xl  font-burtons flex items-center  ml-6   '>Portfolio</h1>

            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl ' />
              </li>
              <li><a className='bg-gradient-to-r from-gray-500 to-zinc-700 text-white px-4 py-2 rounded-md ml-8' href='https://github.com/GIFT2105' target='blank'>Github</a></li>
            </ul>
          </nav>
          <div className='text-center mt-6 rounded-3xl bg-white text-black p-10 '>
            <Image className='mx-auto rounded-3xl dark:bg-black' src={Memoji} width={100} height={100}></Image>
            <h2 className=' mt-6 text-5xl py-2 text-black font-medium font-burtons' >Gift Letuka</h2>
            <h3 className='text-2xl py-2'>Frontend Developer</h3>
            <p className='text-xl py-5 leading-8 text-black text-center'>
              Front-end developer specializing in React.js, Next.js, HTML, CSS, and JavaScript, with experience in Redux, Tailwind CSS, Bootstrap, React Native, REST API,Python and MySQL, has a strong foundation in building modern web applications. Currently pursuing mysecond year in a Bachelor of Science degree, actively expanding my knowledge and skills in the field. my expertise lies in creating responsive and interactive user interfaces, integrating APIs, and utilizing popular frameworks and libraries to deliver high-quality software solutions.
            </p>

          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-white mt-10'>
            <a href='https://www.linkedin.com/in/gift-l-763160295/' target='blank'><AiFillLinkedin /><p className='text-sm '>Linkedin </p></a>
            <a href='/'> <AiFillInstagram /><p className='text-sm'>Instagram</p></a>
            <a href='https://github.com/GIFT2105' target='blank'>   <AiFillGithub /><p className='text-sm'>Github</p></a>



          </div>


          {/*        
  i could potentially bring this div back if i dont like this current design 

          <div className="relative mx-auto  rounded-full w-80 h-80 mt-20 overflow-hidden " >
         <Image src={Memoji} className='ml-11 '  layout='fill' objectFit='cover' ></Image>
          </div>

   */}

        </section>

        {/*        
 skills section

   */}

        <section className='mb-14 mt-14 h-auto w-auto '>
          <h1 className='text-white text-center mt-2 font-burtons text-4xl  items-center '>Skills</h1>
          <div className='flex  justify-center items-center mt-4 h-48 rounded-3xl text-center bg-white '>

            <li>Front-End Development:
              React.js, Next.js, HTML, CSS, JavaScript</li>
            <li>UI Frameworks: Tailwind CSS, Bootstrap</li>
            <li>State Management: Redux</li>
            <li>Mobile Development: React Native</li>
            <li>API Integration: Experience working with REST APIs</li>
            <li>Backend Skills: Python, MySQL</li>
            <li>Git</li>

          </div>
        </section>





        {/* 
        First section:Name,surname,skills summary and the icon with github buttons 
        and social media links
        Second section:projects and contact me form
      */}


        <section>
          <h3 className='text-4xl text-white font-burtons mb-2 py-1 mt-10 text-center'>
            Projects
          </h3>
          <p className='text-xl py-5 bg-white leading-8 text-black rounded-2xl  text-center' >
            As a front-end developer specializing in React.js, Next.js, HTML, CSS, JavaScript, Redux, Tailwind CSS, Bootstrap, React Native, REST API, MySQL, and Python, I have worked on a diverse range of projects to showcase my expertise. Some of the notable projects I have completed include:
          </p>

          <h3 className='text-4xl text-white font-burtons   mt-20 text-center'>
            Cars.co.za Clone
          </h3>
          <div className='flex flex-col items-center'>
            <div className='text-center border-4 h-auto w-auto  bg-white    border-purple-200 shadow-teal-200 shadow-lg p-14 rounded-xl mt-4 '>
              <Image className='mx-auto' src={View} width={1000} height={1000} />
              <p className='text-2xl   font-serif  py-5 leading-10  text-black text-center'>
                The Cars.co.za website clone is a meticulously crafted replica of the original Cars.co.za platform, tailored to imitate its design and functionality. Developed using cutting-edge technologies, including Next.js and Tailwind CSS, the clone offers a seamless user experience with its responsive and visually appealing interface. In addition, the website integrates CarsByNinjaAPI, ensuring real-time access to a vast database of car-related information. Users can explore an extensive range of vehicles, compare specifications, read expert reviews, and find the best deals, all within a user-friendly environment reminiscent of the Cars.co.za website.

                The Cars.co.za website clone not only leverages Next.js and Tailwind CSS but is also powered by TypeScript, a statically typed superset of JavaScript. TypeScript enhances the development process by providing type checking at compile time, leading to more robust and maintainable code. This integration ensures a high level of code quality, making the website clone reliable, efficient, and scalable. Users can enjoy a smooth browsing experience while developers benefit from the enhanced productivity and error prevention offered by TypeScript. </p>

              <h3 className='text-4xl font-burtons   mt-20 text-center'>
                Tech Stack:
              </h3>
              <ul className='flex flex-row mt-5 font-new  text-xl'>
                <li>  - Next.js: React framework for server-side rendering and routing.</li>
                <li> - React: JavaScript library for building dynamic user interfaces.</li>
                <li>- TypeScript: Statically typed superset of JavaScript for improved code quality.</li>
                <li>-  Tailwind CSS: Highly customizable CSS framework with utility classes.</li>
                <li>- Git</li>

              </ul>

              <p className='flex flex-row mt-10 font-new  text-xl  mb-4'  >Demo Link: <a href='https://cars-clone.vercel.app/' target='blank' className='text-blue-500 ml-3 '> https://cars-clone.vercel.app/</a></p>
              <p className='flex flex-row mt-10 font-new  text-xl  mb-4'  >Github Link: <a href='https://cars-clone.vercel.app/' target='blank' className='text-blue-500 ml-3 '>https://github.com/GIFT2105/cars.CO</a></p>
            </div >


            <h3 className='text-4xl text-white font-burtons   mt-20 text-center'>
             Nextjs Developer Portfolio
            </h3>
            <div className='flex flex-col items-center'>
              <div className='text-center border-4 h-auto w-auto  bg-white    border-purple-200 shadow-teal-200 shadow-lg p-14 rounded-xl mt-4 '>
                <Image className='mx-auto' src={View5} width={1000} height={1000} />
                <p className='text-2xl   font-serif  py-5 leading-10  text-black text-center'>
                A Next.js Tailwind CSS portfolio for a front-end developer is a professional website showcasing the developer's skills, projects, and expertise using Next.js, a React framework for server-rendered applications, and Tailwind CSS, a utility-first CSS framework. This portfolio features a responsive and visually appealing design with smooth navigation. It includes sections like About Me, Projects, Skills, Education and Contact Information. The use of Next.js allows for fast loading and seamless user interactions, while Tailwind CSS ensures consistent and visually pleasing styles across the portfolio. Interactive UI elements and animations might be incorporated to enhance user engagement and demonstrate the developer's proficiency in creating modern web experiences. </p>

                <h3 className='text-4xl font-burtons   mt-20 text-center'>
                  Tech Stack:
                </h3>
                <ul className='flex flex-row mt-5 font-new  text-xl'>
                  <li>  - Next.js: React framework for server-side rendering and routing.</li>
                  <li> - React: JavaScript library for building dynamic user interfaces.</li>
                  <li>- JavaScript (ES6+): Modern JavaScript (ES6 and above) is the backbone of the application, enabling dynamic content rendering, interactivity, and smooth user experiences.</li>
                  <li>-  Tailwind CSS: Highly customizable CSS framework with utility classes.</li>
                  <li>- Git</li>

                </ul>

                <p className='flex flex-row mt-10 font-new  text-xl  mb-4'  >Github Link: <a href='https://cars-clone.vercel.app/' target='blank' className='text-blue-500 ml-3 '>https://github.com/GIFT2105/cars.CO</a></p>
              </div >








              <h3 className='text-4xl text-white font-burtons   mt-20 text-center'>
                CareerRoutes-101
              </h3>
              <div className='flex flex-col items-center'>
                <div className='text-center border-4 h-auto w-auto  bg-white    border-purple-200 shadow-teal-200 shadow-lg p-14 rounded-xl mt-4 '>
                  <Image className='mx-auto' src={View3} width={1000} height={1000} />
                  <p className='text-xl   font-serif  py-5 leading-10  text-black text-center'>
                    The app is an interactive career guidance tool designed to help users explore different career paths based on their preferences and interests. It presents users with a series of questions related to their hobbies, skills, and interests. Based on their answers, the app provides tailored career recommendations from various fields, such as software development, graphic design, teaching, and more. The app aims to assist users, especially students, in making informed decisions about their future careers by suggesting paths that align with their interests.
                    <br />
                    <br />
                    How the App Works:<br />User Interaction: Users interact with the app by answering a series of questions related to their preferences, hobbies, and skills. State Management: React Hooks, specifically useState, manage the state of the user's answers and the current question displayed on the screen. Conditional Rendering: Based on the user's answers, the app conditionally renders different questions and options, guiding the user through the quiz. Career Recommendations: After the user completes the quiz, the app processes their answers using conditional logic. It determines suitable career paths based on the combinations of selected answers. Displaying Recommendations: The app displays the career recommendations to the user, suggesting potential fields they might be interested in pursuing. Additional Features: The app might include extra features, such as detailed descriptions of each career path, educational requirements, skills needed, and steps to succeed in that particular field. This app provides an interactive and engaging way for users to explore potential career options, making use of modern web technologies to create a seamless user experience
                  </p>

                  <h3 className='text-4xl font-burtons   mt-20 text-center'>
                    Tech Stack:
                  </h3>
                  <ul className='flex flex-row mt-5 font-new text-xl'>
                    <li> - React.js: A popular JavaScript library for building user interfaces. React allows for the creation of interactive and dynamic UI components.</li>
                    <li> - Next.js HTML/CSS: Used for structuring the web pages and styling the app's user interface to make it visually appealing and user-friendly.</li>
                    <li> - JavaScript (ES6+): Modern JavaScript (ES6 and above) is the backbone of the application, enabling dynamic content rendering, interactivity, and smooth user experiences.</li>
                    <li> - Tailwind CSS: A utility-first CSS framework used for quickly styling the components and creating a responsive design.</li>
                    <li> - State Management: React Hooks (useState): Utilized for managing state variables within functional components, enabling dynamic updates and re-renders based on user interactions.</li>
                    <li> - Development Environment: Node.js and npm: Node.js is used for running JavaScript on the server side, and npm is the package manager for managing project dependencies.</li>
                    <li> - Firebase Version Control: Git and GitHub: Git is used for version control, enabling collaborative development and tracking changes in the source code. GitHub is a web-based hosting service for Git repositories.</li>
                  </ul>


                  <p className='flex flex-row mt-10 font-new  text-xl  mb-4'  >Demo Link: <a href='https://career-routes101.vercel.app/' target='blank' className='text-blue-500 ml-3 '> https://career-routes101.vercel.app/</a></p>
                  <p className='flex flex-row mt-10 font-new  text-xl  mb-4'  >Github Link: <a href='https://github.com/GIFT2105/CareerRoutes101' target='blank' className='text-blue-500 ml-3 '>https://github.com/GIFT2105/CareerRoutes101</a></p>
                </div >
              </div >



              <h3 className='text-4xl text-white font-burtons   mt-20 text-center'>
                GreenTech Innovations Mockup
              </h3>
              <div className='flex flex-col items-center'>
                <div className='text-center border-4 h-auto w-auto  bg-white    border-purple-200 shadow-teal-200 shadow-lg p-14 rounded-xl mt-4 '>
                  <Image className='mx-auto' src={View4} width={1000} height={1000} />
                  <p className='text-2xl   font-serif  py-5 leading-10  text-black text-center'>
                    🌿 GreenTech Innovations Mockup: Explore a fictional world where sustainability meets innovation! This Next.js project showcases a mockup website for 'GreenTech Innovations,' a visionary company committed to eco-friendly solutions. Dive into the future of green technology with our interactive demo  </p>

                  <h3 className='text-4xl font-burtons   mt-20 text-center'>
                    Tech Stack:
                  </h3>
                  <ul className='flex flex-row mt-5 font-new text-xl'>
                    <li>Next.js: Next.js is a React framework that provides server-rendered React applications and static site generation. It offers a robust foundation for building fast and dynamic web applications.</li>
                    <li>React: React is a popular JavaScript library for building user interfaces. It allows for the creation of reusable UI components, enabling the development of interactive and responsive web applications.</li>
                    <li>JavaScript (ES6+): Modern JavaScript (ES6 and above) is the backbone of the application, enabling dynamic content rendering, interactivity, and smooth user experiences.</li>
                    <li>CSS Modules: CSS Modules allow for modular and scoped styling, ensuring that styles are encapsulated within components and do not conflict with each other.</li>
                    <li>HTML5: The latest version of HTML provides semantic structure to the web content, enhancing accessibility and search engine optimization.</li>
                    <li>Version Control (Git, GitHub): Git is used for version control, allowing collaborative development and tracking changes. The project is hosted on GitHub, providing a centralized repository for collaboration and version history.</li>
                  </ul>
                  <p className='flex flex-row mt-5 font-new text-md'>By leveraging these technologies, GreenTech Innovations Mockup delivers an engaging and immersive user experience, showcasing the potential of technology in driving environmental sustainability.</p>


                  <p className='flex flex-row mt-10 font-new  text-xl  mb-4'  >Demo Link: <a href='https://green-tech-fake-company-site.vercel.app/' target='blank' className='text-blue-500 ml-3 '> https://green-tech-fake-company-site.vercel.app/</a></p>
                  <p className='flex flex-row mt-10 font-new  text-xl  mb-4'  >Github Link: <a href='https://github.com/GIFT2105/GreenTechFakeCompanySite' target='blank' className='text-blue-500 ml-3 '>https://github.com/GIFT2105/GreenTechFakeCompanySite</a></p>
                </div >
              </div >




              <h3 className='text-4xl text-white font-burtons   mt-20 text-center'>
                SAbuilds-101
              </h3>
              <div className='flex flex-col items-center'>
                <div className='text-center border-4 h-auto w-auto  bg-white    border-purple-200 shadow-teal-200 shadow-lg p-14 rounded-xl mt-4 '>
                  <Image className='mx-auto' src={View2} width={1000} height={1000} />
                  <p className='text-2xl   font-serif  py-5 leading-10  text-black text-center'>
                    a dynamic car blog app designed for passionate car enthusiasts to come together and share their innovative car build ideas. This platform is built using cutting-edge technologies, including React with Vite for a lightning-fast frontend experience and Tailwind CSS for sleek, responsive design. Behind the scenes, Firebase Firestore handles real-time data storage, ensuring seamless collaboration and discussion among users. Additionally, Firebase Storage supports effortless media uploads, allowing users to showcase their car projects with ease. With a user-friendly UI, this app fosters a vibrant community of car enthusiasts, encouraging the exchange of creative car build ideas and inspiring the next generation of automotive innovation.  </p>

                  <h3 className='text-4xl font-burtons   mt-20 text-center'>
                    Tech Stack:
                  </h3>
                  <ul className='flex flex-row mt-5 font-new  text-xl'>
                    <li>  - Frontend Technologies:
                      React with Vite
                    </li>
                    <li> - React-icons.</li>
                    <li>- Firebase Firestore (Real-time Database)</li>
                    <li>- Firebase Storage (Media Storage)</li>
                    <li>- Git</li>
                    <li>-  Tailwind CSS: Highly customizable CSS framework with utility classes.</li>
                    <li>- UUID (User Interface Framework) These technologies work together to create a seamless and user-friendly platform for car enthusiasts to share their car build ideas and collaborate with one another </li>


                  </ul>

                  <p className='flex flex-row mt-10 font-new  text-xl  mb-4'  >Demo Link: <a href='https://gift2105.github.io/SAbuilds-car-blog-app/' target='blank' className='text-blue-500 ml-3 '> https://gift2105.github.io/SAbuilds-car-blog-app/</a></p>
                  <p className='flex flex-row mt-10 font-new  text-xl  mb-4'  >Github Link: <a href='https://github.com/GIFT2105/cars.CO' target='blank' className='text-blue-500 ml-3 '>https://github.com/GIFT2105/cars.CO</a></p>
                </div >
              </div >




            </div>

            <h3 className='text-2xl text-white font-burtons   mt-20 text-center'>
           <a className='text-blue-500' href='https://github.com/GIFT2105'>See More Projects on Github</a>
          </h3>
          </div>
          </section>
          <section class="bg-white p-6">
          <h3 class="text-2xl font-bold mb-4">Contact Me</h3>
          <form class="flex flex-col space-y-4">
              <div class="flex flex-col">
                  <label for="name" class="text-sm font-semibold mb-2">Name</label>
                  <input type="text" id="name" name="name" class="border p-2 rounded-md" placeholder="Enter your name" required/>
              </div>
              <div class="flex flex-col">
                  <label for="email" class="text-sm font-semibold mb-2">Email</label>
                  <input type="email" id="email" name="email" class="border p-2 rounded-md" placeholder="Enter your email" required/>
              </div>
              <div class="flex flex-col">
                  <label for="message" class="text-sm font-semibold mb-2">Message</label>
                  <textarea id="message" name="message" class="border p-2 rounded-md" placeholder="Enter your message" rows="4" required></textarea>
              </div>
              <button type="submit" class="bg-blue-500 text-white font-semibold py-2 rounded-md hover:bg-blue-700 transition duration-300">Submit</button>
          </form>
      </section>
     
      
    
      </main>
      
    </div>
    
  );
}
